// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 1.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_1_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_1_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_1_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_1_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_1_2eproto;
class User;
struct UserDefaultTypeInternal;
extern UserDefaultTypeInternal _User_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::User* Arena::CreateMaybeMessage<::User>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class User final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:User) */ {
 public:
  inline User() : User(nullptr) {}
  ~User() override;
  explicit PROTOBUF_CONSTEXPR User(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  User(const User& from);
  User(User&& from) noexcept
    : User() {
    *this = ::std::move(from);
  }

  inline User& operator=(const User& from) {
    CopyFrom(from);
    return *this;
  }
  inline User& operator=(User&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const User& default_instance() {
    return *internal_default_instance();
  }
  static inline const User* internal_default_instance() {
    return reinterpret_cast<const User*>(
               &_User_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(User& a, User& b) {
    a.Swap(&b);
  }
  inline void Swap(User* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(User* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  User* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<User>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const User& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const User& from) {
    User::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(User* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "User";
  }
  protected:
  explicit User(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kArrFieldNumber = 2,
    kStuFieldNumber = 3,
    kAgeFieldNumber = 1,
  };
  // repeated string arr = 2;
  int arr_size() const;
  private:
  int _internal_arr_size() const;
  public:
  void clear_arr();
  const std::string& arr(int index) const;
  std::string* mutable_arr(int index);
  void set_arr(int index, const std::string& value);
  void set_arr(int index, std::string&& value);
  void set_arr(int index, const char* value);
  void set_arr(int index, const char* value, size_t size);
  std::string* add_arr();
  void add_arr(const std::string& value);
  void add_arr(std::string&& value);
  void add_arr(const char* value);
  void add_arr(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& arr() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_arr();
  private:
  const std::string& _internal_arr(int index) const;
  std::string* _internal_add_arr();
  public:

  // string stu = 3;
  void clear_stu();
  const std::string& stu() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_stu(ArgT0&& arg0, ArgT... args);
  std::string* mutable_stu();
  PROTOBUF_NODISCARD std::string* release_stu();
  void set_allocated_stu(std::string* stu);
  private:
  const std::string& _internal_stu() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_stu(const std::string& value);
  std::string* _internal_mutable_stu();
  public:

  // int32 age = 1;
  void clear_age();
  int32_t age() const;
  void set_age(int32_t value);
  private:
  int32_t _internal_age() const;
  void _internal_set_age(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:User)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> arr_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr stu_;
    int32_t age_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_1_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// User

// int32 age = 1;
inline void User::clear_age() {
  _impl_.age_ = 0;
}
inline int32_t User::_internal_age() const {
  return _impl_.age_;
}
inline int32_t User::age() const {
  // @@protoc_insertion_point(field_get:User.age)
  return _internal_age();
}
inline void User::_internal_set_age(int32_t value) {
  
  _impl_.age_ = value;
}
inline void User::set_age(int32_t value) {
  _internal_set_age(value);
  // @@protoc_insertion_point(field_set:User.age)
}

// repeated string arr = 2;
inline int User::_internal_arr_size() const {
  return _impl_.arr_.size();
}
inline int User::arr_size() const {
  return _internal_arr_size();
}
inline void User::clear_arr() {
  _impl_.arr_.Clear();
}
inline std::string* User::add_arr() {
  std::string* _s = _internal_add_arr();
  // @@protoc_insertion_point(field_add_mutable:User.arr)
  return _s;
}
inline const std::string& User::_internal_arr(int index) const {
  return _impl_.arr_.Get(index);
}
inline const std::string& User::arr(int index) const {
  // @@protoc_insertion_point(field_get:User.arr)
  return _internal_arr(index);
}
inline std::string* User::mutable_arr(int index) {
  // @@protoc_insertion_point(field_mutable:User.arr)
  return _impl_.arr_.Mutable(index);
}
inline void User::set_arr(int index, const std::string& value) {
  _impl_.arr_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:User.arr)
}
inline void User::set_arr(int index, std::string&& value) {
  _impl_.arr_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:User.arr)
}
inline void User::set_arr(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.arr_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:User.arr)
}
inline void User::set_arr(int index, const char* value, size_t size) {
  _impl_.arr_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:User.arr)
}
inline std::string* User::_internal_add_arr() {
  return _impl_.arr_.Add();
}
inline void User::add_arr(const std::string& value) {
  _impl_.arr_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:User.arr)
}
inline void User::add_arr(std::string&& value) {
  _impl_.arr_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:User.arr)
}
inline void User::add_arr(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.arr_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:User.arr)
}
inline void User::add_arr(const char* value, size_t size) {
  _impl_.arr_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:User.arr)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
User::arr() const {
  // @@protoc_insertion_point(field_list:User.arr)
  return _impl_.arr_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
User::mutable_arr() {
  // @@protoc_insertion_point(field_mutable_list:User.arr)
  return &_impl_.arr_;
}

// string stu = 3;
inline void User::clear_stu() {
  _impl_.stu_.ClearToEmpty();
}
inline const std::string& User::stu() const {
  // @@protoc_insertion_point(field_get:User.stu)
  return _internal_stu();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void User::set_stu(ArgT0&& arg0, ArgT... args) {
 
 _impl_.stu_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:User.stu)
}
inline std::string* User::mutable_stu() {
  std::string* _s = _internal_mutable_stu();
  // @@protoc_insertion_point(field_mutable:User.stu)
  return _s;
}
inline const std::string& User::_internal_stu() const {
  return _impl_.stu_.Get();
}
inline void User::_internal_set_stu(const std::string& value) {
  
  _impl_.stu_.Set(value, GetArenaForAllocation());
}
inline std::string* User::_internal_mutable_stu() {
  
  return _impl_.stu_.Mutable(GetArenaForAllocation());
}
inline std::string* User::release_stu() {
  // @@protoc_insertion_point(field_release:User.stu)
  return _impl_.stu_.Release();
}
inline void User::set_allocated_stu(std::string* stu) {
  if (stu != nullptr) {
    
  } else {
    
  }
  _impl_.stu_.SetAllocated(stu, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.stu_.IsDefault()) {
    _impl_.stu_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:User.stu)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_1_2eproto
